apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wg-overlay-service
  namespace: wireguard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-operator
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wg-overlay
subjects:
- kind: ServiceAccount
  name: wg-overlay-service
  namespace: wireguard
roleRef:
  kind: ClusterRole
  name: node-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: wg-overlay
  name: wireguard-network-service
  namespace: wireguard
spec:
  selector:
    matchLabels:
      k8s-app: wg-overlay
  template:
    metadata:
      labels:
        k8s-app: wg-overlay
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      terminationGracePeriodSeconds: 0
      serviceAccountName: wg-overlay-service
      volumes:
      - name: wg-vol
        hostPath:
          path: /etc/wireguard
          type: DirectoryOrCreate
      containers:
      - name: wnc
        image: tylloyd/wg-network-service:v20220301-a
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        command: ['/wnc']
        args:
        - --node-name=$(NODE_NAME)
        - --node-ip=$(NODE_IP)
        - --public-key=$(< /etc/wireguard/publickey)
        volumeMounts:
        - mountPath: /etc/wireguard
          name: wg-vol
      - name: wireguard-network-service
        env:
        - name: OVERLAY_CIDR
          value: 100.64.0.0/16
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        image: tylloyd/wg-network-service:v20220301-a
        imagePullPolicy: Always
        command: ["/wireguard-network-service"]
        volumeMounts:
        - mountPath: /etc/wireguard
          name: wg-vol
      - name: wns-sync
        image: busybox:latest
        securityContext:
          privileged: true
        command:
          - nsenter
          - --target
          - "1"
          - --mount
          - --uts
          - --ipc
          - --net
          - --pid
          - --
          - bash
          - -ce
          - |
            while :
            do
              echo "checking wireguard config ... "
              if [ -f "/etc/wireguard/update" ]; then
                echo "updating wg-quick@wg0.service"
                systemctl restart wg-quick@wg0.service
                rm /etc/wireguard/update
              else
                echo "re-sync in 5 sec"
              fi
              sleep 5
            done
      initContainers:
      - name: wireguard-install
        image: busybox:latest
        securityContext:
          privileged: true
        command:
          - nsenter
          - --target
          - "1"
          - --mount
          - --uts
          - --ipc
          - --net
          - --pid
          - --
          - bash
          - -ce
          - |
            echo "Installing wireguard..."
            sudo apt update
            sudo apt install -y wireguard
      - name: wg-init
        image: tylloyd/wg-network-service:latest
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        securityContext:
          privileged: true
        command: ['/wg-init']
        args:
        - --node-ip=$(NODE_IP)
