apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wg-overlay-service
  namespace: wireguard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-operator
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wg-overlay
subjects:
- kind: ServiceAccount
  name: wg-overlay-service
  namespace: wireguard
roleRef:
  kind: ClusterRole
  name: node-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: wg-overlay
  name: wireguard-network-service
  namespace: wireguard
spec:
  selector:
    matchLabels:
      k8s-app: wg-overlay
  template:
    metadata:
      labels:
        k8s-app: wg-overlay
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      terminationGracePeriodSeconds: 0
      serviceAccountName: wg-overlay-service
      containers:
      - name: wnc
        image: tylloyd/wg-network-service:latest
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        command: ['/wnc']
        args:
        - --node-name=$(NODE_NAME)
        - --node-ip=$(NODE_IP)
      initContainers:
      - name: wireguard-install
        image: busybox:latest
        securityContext:
          privileged: true
        command:
          - nsenter
          - --target
          - "1"
          - --mount
          - --uts
          - --ipc
          - --net
          - --pid
          - --
          - bash
          - -c
          - |
            echo 'installing wireguard'
            found=$(dpkg -s wireguard | grep 'install ok installed')
            if [ "$found" = "" ];
            then
              sudo apt update
              sudo apt install -y wireguard
            else
              echo 'wireguard already installed'
            fi
      - name: wg-init
        image: tylloyd/wg-network-service:latest
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        securityContext:
          privileged: true
        command: ['/wg-init']
        args:
        - --node-ip=$(NODE_IP)
